export const copy = {
  appTitle: 'Le Scribe du Royaume',
  homeSubtitle: 'Compte les points de ta main',
  homeBase: 'Jeu de base',
  homeBaseSub: '7 cartes',
  homeExt: 'Extension',
  homeExtSub: 'Le Trésor maudit',
  modulesTitle: 'Le Trésor maudit',
  modulesQuestion: 'Avec quoi joues-tu ?',
  modulesFamilies: 'Familles supplémentaires',
  modulesFamiliesSub: 'Bâtiments, Extérieurs et Morts-vivants · 8 cartes',
  modulesCursed: 'Objets maudits',
  modulesCursedSub: '7 cartes',
  modulesFull: 'Les deux',
  modulesFullSub: 'Le Trésor maudit complet · 8 cartes',
  setupTitle: 'Que veux-tu compter ?',
  setupSingle: 'Une main',
  setupSingleSub: 'Calcule une main à la fois',
  setupGame: 'Une partie',
  setupGameSub: 'Compte la main de chaque joueur et désigne le gagnant',
  setupPlayers: 'Nombre de joueurs',
  setupStart: 'Commencer la partie',
  gamePlayer: (n: number) => `Joueur ${n}`,
  gamePlayerOf: (n: number, total: number, name: string | null) =>
    name ? `${name} · ${n} sur ${total}` : `Joueur ${n} sur ${total}`,
  setupNames: 'Saisir les noms des joueurs',
  gameNext: 'Joueur suivant',
  gameRanking: 'Voir le classement',
  gameAbandon: 'Abandonner la partie',
  gameAbandonConfirm: 'Abandonner cette partie ?',
  rankingTitle: 'Classement',
  rankingWins: 'remporte la partie',
  rankingTie: (players: string) => `Égalité entre ${players}`,
  rankingNew: 'Nouvelle partie',
  handTitle: 'Ta main',
  handPlaceholder: "Tape le nom d'une carte",
  handNoMatch: (q: string) => `Aucune carte ne correspond à « ${q} »`,
  handRemove: (nom: string) => `Retirer ${nom}`,
  handAbandon: 'Abandonner cette main ?',
  handMissing: (n: number) => `Il manque ${n} carte${n > 1 ? 's' : ''} pour compléter ta main.`,
  handFirstCard: 'Ta première carte',
  yes: 'Oui',
  no: 'Non',
  back: 'Retour',
  cursedTitle: 'Objets maudits',
  cursedHelp: "Ajoute les objets retournés face cachée. L'objet encore face visible ne compte pas.",
  cursedPlaceholder: "Tape le nom d'un objet",
  cursedNoMatch: (q: string) => `Aucun objet ne correspond à « ${q} »`,
  cursedNone: 'Aucun objet',
  cursedTotal: (n: string) => `Total des objets : ${n}`,
  bonusTitle: 'Carte bonus',
  bonusNecro: 'Tu as le Nécromancien : quelle carte as-tu récupérée dans la défausse ?',
  bonusDraw: (source: string) => `Tu as ${source} : quelle carte as-tu piochée ?`,
  bonusSeveral: (sources: string) => `Carte supplémentaire (${sources})`,
  bonusSkip: 'Pas de carte bonus',
  bonusChange: 'Changer',
  jokersTitle: 'Jokers',
  jokersCopies: (nameWithArticle: string) =>
    `${nameWithArticle.charAt(0).toUpperCase()}${nameWithArticle.slice(1)} copie :`,
  jokersNone: 'Ne copie rien',
  bookTitle: 'Livre des mutations',
  bookTarget: 'Quelle carte change de famille ?',
  bookFamily: (carte: string) => `${carte} devient :`,
  bookResult: (carte: string, famille: string) => `${carte} devient ${famille}`,
  bookNone: 'Ne change rien',
  islandTitle: 'Île',
  islandQuestion: "L'Île efface le malus de :",
  islandNone: "N'efface rien",
  angelTitle: 'Ange',
  angelQuestion: "L'Ange protège :",
  angelNone: 'Ne protège rien',
  endTitle: 'Fin de partie',
  endPlayers: 'Nombre de joueurs',
  endDiscard: 'Défausse en fin de partie',
  endDiscardHelp: 'Compte les cartes de la zone de défausse (y compris celles sous la Chambre forte).',
  endLicorne: 'La Licorne est dans la défausse',
  endStepperMinus: (famille: string) => `Retirer une carte ${famille}`,
  endStepperPlus: (famille: string) => `Ajouter une carte ${famille}`,
  endStepperValue: (famille: string, n: number) => `${famille} : ${n}`,
  ctaContinue: 'Continuer',
  ctaScore: 'Compter les points',
  resultTitle: 'Résultat',
  resultPoints: 'points',
  resultMasked: 'Masquée',
  resultCleared: 'Malus effacé',
  resultArmyWordCleared: 'Mot Armée effacé',
  resultMaskedBy: (nameWithArticle: string) => `par ${nameWithArticle}`,
  resultSelfMasked: 'par son propre malus',
  resultNoFlame: 'sans Flamme',
  resultNoFlood: 'sans Vague',
  resultNoArmy: 'sans Armée',
  resultWithWeather: 'avec un Climat',
  resultWithFlood: 'avec une Vague',
  resultCursed: 'Objets maudits',
  resultTiebreak: (n: number) => `Départage : force de base totale ${n}`,
  resultNew: 'Nouvelle main',
  rankRuins: 'Un royaume en ruines',
  rankFief: 'Un modeste fief',
  rankProsperous: 'Un royaume prospère',
  rankEmpire: 'Un empire redouté',
  rankLegend: 'Une légende des royaumes',
  resultEdit: 'Modifier la main',
  resultMode: 'Changer de mode',
};

export const SOURCE_WITH_ARTICLE: Record<'FR28' | 'CH09' | 'CH06' | 'CH46', string> = {
  FR28: 'le Nécromancien',
  CH09: 'le Leprechaun',
  CH06: 'le Génie',
  CH46: 'le Portail',
};

export function signed(n: number): string {
  if (n === 0) return '—';
  return n > 0 ? `+${n}` : `−${Math.abs(n)}`;
}

export function number(n: number): string {
  return n < 0 ? `−${Math.abs(n)}` : `${n}`;
}
